package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"errors"
	"fmt"
	"translatorapi/database"
	generated1 "translatorapi/graph/generated"
	"translatorapi/graph/model"
	"translatorapi/models"
)

// CreateWord creates a new Polish word.
func (r *mutationResolver) CreateWord(ctx context.Context, polishWord string) (*model.Word, error) {
	word := models.Word{
		PolishWord: polishWord,
	}

	if err := database.DB.Create(&word).Error; err != nil {
		return nil, err
	}

	return ToGraphQLWord(&word), nil
}

// CreateTranslation creates a new translation for a word.
func (r *mutationResolver) CreateTranslation(ctx context.Context, polishWord string, englishWord string) (*model.Translation, error) {
	// Find the word by its PolishWord
	var word models.Word
	if err := database.DB.Where("polish_word = ?", polishWord).First(&word).Error; err != nil {
		return nil, fmt.Errorf("word not found: %v", err)
	}

	// Create the translation for the found word
	translation := models.Translation{
		WordID:      word.ID,
		EnglishWord: englishWord,
	}

	if err := database.DB.Create(&translation).Error; err != nil {
		return nil, err
	}

	return ToGraphQLTranslation(&translation), nil
}

// CreateExample creates a new example sentence for a translation.
func (r *mutationResolver) CreateExample(ctx context.Context, englishWord string, sentence string) (*model.Example, error) {
	// Find the translation by EnglishWord
	var translation models.Translation
	if err := database.DB.Where("english_word = ?", englishWord).First(&translation).Error; err != nil {
		return nil, fmt.Errorf("translation not found: %v", err)
	}

	// Create the example for the found translation
	example := models.Example{
		TranslationID: translation.ID,
		Sentence:      sentence,
	}

	if err := database.DB.Create(&example).Error; err != nil {
		return nil, err
	}

	return ToGraphQLExample(&example), nil
}

// CreateWordWithTranslation is the resolver for the createWordWithTranslation field.
func (r *mutationResolver) CreateWordWithTranslation(ctx context.Context, polishWord string, englishWord string) (*model.Word, error) {
	word := models.Word{
		PolishWord: polishWord,
	}
	if err := database.DB.Create(&word).Error; err != nil {
		return nil, err
	}
	if word.ID == 0 {
		return nil, errors.New("failed to retrieve Word ID after creation")
	}
	translation := models.Translation{
		EnglishWord: englishWord,
		WordID:      word.ID,
	}
	if err := database.DB.Create(&translation).Error; err != nil {
		return nil, err
	}
	// Preload translations so GraphQL can access them
	var completeWord models.Word
	if err := database.DB.Preload("Translations").First(&completeWord, word.ID).Error; err != nil {
		return nil, err
	}
	return ToGraphQLWord(&completeWord), nil
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, polishWord string) (bool, error) {
	if err := database.DB.Where("polish_word = ?", polishWord).Delete(&models.Word{}).Error; err != nil {
		return false, err
	}
	return true, nil
}

// DeleteTranslation is the resolver for the deleteTranslation field.
func (r *mutationResolver) DeleteTranslation(ctx context.Context, polishWord string, englishWord string) (bool, error) {
	var word models.Word
	if err := database.DB.Where("polish_word = ?", polishWord).First(&word).Error; err != nil {
		return false, err
	}
	if err := database.DB.Where("word_id = ? AND english_word = ?", word.ID, englishWord).Delete(models.Translation{}).Error; err != nil {
		return false, err
	}

	return true, nil
}

// Words is the resolver for the words field.
func (r *queryResolver) Words(ctx context.Context) ([]*model.Word, error) {
	var words []*models.Word
	if err := database.DB.Preload("Translations").Find(&words).Error; err != nil {
		return nil, err
	}

	var gqlWords []*model.Word
	for _, word := range words {
		gqlWords = append(gqlWords, ToGraphQLWord(word))
	}

	return gqlWords, nil
}

// Translations retrieves translations by PolishWord.
func (r *queryResolver) Translations(ctx context.Context, polishWord string) ([]*model.Translation, error) {
	var word models.Word
	if err := database.DB.Where("polish_word = ?", polishWord).First(&word).Error; err != nil {
		return nil, fmt.Errorf("word not found: %v", err)
	}

	var translations []*models.Translation
	if err := database.DB.Where("word_id = ?", word.ID).Find(&translations).Error; err != nil {
		return nil, fmt.Errorf("could not fetch translations: %v", err)
	}

	var gqlTranslations []*model.Translation
	for _, translation := range translations {
		gqlTranslations = append(gqlTranslations, ToGraphQLTranslation(translation))
	}

	return gqlTranslations, nil
}

// Examples retrieves examples by EnglishWord.
func (r *queryResolver) Examples(ctx context.Context, englishWord string) ([]*model.Example, error) {
	var translation models.Translation
	if err := database.DB.Where("english_word = ?", englishWord).First(&translation).Error; err != nil {
		return nil, fmt.Errorf("translation not found: %v", err)
	}

	var examples []*models.Example
	if err := database.DB.Where("translation_id = ?", translation.ID).Find(&examples).Error; err != nil {
		return nil, err
	}

	var gqlExamples []*model.Example
	for _, example := range examples {
		gqlExamples = append(gqlExamples, ToGraphQLExample(example))
	}

	return gqlExamples, nil
}

// Mutation returns generated1.MutationResolver implementation.
func (r *Resolver) Mutation() generated1.MutationResolver { return &mutationResolver{r} }

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
