// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Example struct {
	ID            string `json:"id"`
	TranslationID string `json:"translationID"`
	Sentence      string `json:"sentence"`
}

type Mutation struct {
}

type Query struct {
}

type Translation struct {
	ID          string     `json:"id"`
	WordID      string     `json:"wordID"`
	EnglishWord string     `json:"englishWord"`
	Examples    []*Example `json:"examples"`
}

type Word struct {
	ID           string         `json:"id"`
	PolishWord   string         `json:"polishWord"`
	Translations []*Translation `json:"translations"`
}
